import { useMemo, useState } from "react";
import { getPlanningBudget } from "../../domains/orcamentos/calculations";
import {
  buildBudgetMaterialDemand, createAbcSnapshot, createSupplyPlan, defaultSupplySettings,
  DEFAULT_LEAD_PROFILES,
} from "../../domains/suprimentos/calculations";

const now = () => new Date().toISOString();
const id = prefix => `${prefix}-${globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
const money = value => Number(value || 0).toLocaleString("pt-BR", { style:"currency", currency:"BRL" });
const date = value => value ? new Intl.DateTimeFormat("pt-BR", { timeZone:"UTC" }).format(new Date(`${value}T00:00:00Z`)) : "—";
const colorRisk = risk => ({ critico:"#b42318", alto:"#b54708", medio:"#8a6d1d", baixo:"#287a47" }[risk] || "#667085");
const canApprove = user => ["admin", "engenheiro_auditor"].includes(user?.role);

const Shell = ({ children }) => <div style={{ maxWidth:1420, margin:"0 auto", padding:"8px 0 30px", color:"#27313d" }}>{children}</div>;
const Panel = ({ children, style = {} }) => <section style={{ background:"#fcfcfb", border:"1px solid #d7dde2", borderRadius:10, ...style }}>{children}</section>;
const Button = ({ children, secondary = false, ...props }) => <button {...props} style={{ border:`1px solid ${secondary ? "#c8d0d8" : "#b7941e"}`, color:secondary ? "#344054" : "#2d250a", background:secondary ? "#fff" : "#d8b52a", borderRadius:6, minHeight:34, padding:"0 12px", fontSize:11, fontWeight:800, cursor:props.disabled ? "not-allowed" : "pointer", opacity:props.disabled ? .55 : 1, ...props.style }}>{children}</button>;

export default function MarcosCurvaASuprimentos({ data, update, showToast, currentUser, obraIdFixo = "" }) {
  const works = data.obras || [];
  const [obraId, setObraId] = useState(() => obraIdFixo || works[0]?.id || "");
  const [view, setView] = useState("visao");
  const [selectedId, setSelectedId] = useState("");
  const [profileId, setProfileId] = useState("nacional");
  const plan = useMemo(() => (data.planos || []).find(item => item.obraId === obraId), [data.planos, obraId]);
  const planning = useMemo(() => getPlanningBudget(data, obraId, plan), [data, obraId, plan]);
  const tasks = plan?.tarefas || [];
  const settings = { ...defaultSupplySettings(), ...(data.suprimentosConfig || {}), abc:{ ...defaultSupplySettings().abc, ...(data.suprimentosConfig?.abc || {}) }, calendario:{ ...defaultSupplySettings().calendario, ...(data.suprimentosConfig?.calendario || {}) } };
  const profiles = Array.isArray(settings.perfisLeadTime) && settings.perfisLeadTime.length ? settings.perfisLeadTime : DEFAULT_LEAD_PROFILES;
  const demands = useMemo(() => buildBudgetMaterialDemand({ budget:planning.budget, materials:data.materiais || [], tasks }), [planning.budget, data.materiais, tasks]);
  const snapshots = useMemo(() => (data.curvaAbcSnapshots || []).filter(item => item.obraId === obraId).sort((a,b) => String(b.createdAt).localeCompare(String(a.createdAt))), [data.curvaAbcSnapshots, obraId]);
  const activeSnapshot = snapshots.find(item => item.status === "aprovado") || null;
  const supplyPlans = useMemo(() => (data.planosSuprimento || []).filter(item => item.obraId === obraId && item.snapshotId === activeSnapshot?.id && item.status !== "cancelado"), [data.planosSuprimento, obraId, activeSnapshot]);
  const selected = supplyPlans.find(item => item.id === selectedId) || supplyPlans[0] || null;
  const summary = useMemo(() => {
    const value = supplyPlans.reduce((sum,item) => sum + Number(item.quantidadeOrcada || 0) * (activeSnapshot?.itens || []).find(x => x.materialId === item.materialId)?.custoTotal / Math.max(1, (activeSnapshot?.itens || []).find(x => x.materialId === item.materialId)?.quantidade || 1), 0);
    return { value, risk:Object.fromEntries(["critico","alto","medio","baixo"].map(level => [level,supplyPlans.filter(item => item.risco === level).length])), withoutOrder:supplyPlans.filter(item => !item.pedidoIds?.length).length, pending:supplyPlans.filter(item => item.vinculo !== "confirmado").length };
  }, [supplyPlans, activeSnapshot]);

  const generateProposal = () => {
    if (!planning.budget) return showToast?.("Cadastre ou vincule um orçamento à obra antes de gerar a Curva ABC.", "error");
    if (!demands.length) return showToast?.("O orçamento ainda não tem insumos analíticos com vínculos explícitos. Não é seguro inferir a Curva A por descrição.", "warn");
    const snapshot = createAbcSnapshot({ id:id("abc"), obraId, budget:planning.budget, baselineVersionId:planning.baseline?.budgetVersionId || "", demands, limits:settings.abc, actor:currentUser, now:now() });
    update({ ...data, curvaAbcSnapshots:[...(data.curvaAbcSnapshots || []), snapshot] });
    showToast?.(`Proposta da Curva ABC criada com ${snapshot.itens.length} insumo(s). Revise e aprove antes de contratar.`);
  };
  const approve = snapshot => {
    if (!canApprove(currentUser)) return showToast?.("A aprovação exige perfil de administrador ou engenheiro auditor.", "error");
    const when = now();
    update({ ...data, curvaAbcSnapshots:(data.curvaAbcSnapshots || []).map(item => item.obraId !== obraId ? item : item.id === snapshot.id ? { ...item, status:"aprovado", approvedAt:when, approvedById:currentUser?.id || "", approvedBy:currentUser?.nome || "", updatedAt:when, version:Number(item.version || 0) + 1 } : item.status === "aprovado" ? { ...item, status:"substituido", replacedAt:when, replacedBySnapshotId:snapshot.id } : item) });
    showToast?.("Snapshot aprovado. A versão anterior foi preservada como substituída.");
  };
  const generatePlans = () => {
    if (!activeSnapshot) return showToast?.("Aprove uma Curva ABC antes de gerar planos de suprimento.", "warn");
    const profile = profiles.find(item => item.id === profileId) || profiles[0];
    if (!profile) return showToast?.("Cadastre um perfil de lead time antes de gerar os planos.", "error");
    const byMaterial = new Map(activeSnapshot.itens.map(item => [item.materialId, item]));
    const existing = new Set((data.planosSuprimento || []).filter(item => item.obraId === obraId && item.snapshotId === activeSnapshot.id).map(item => item.materialId));
    const created = activeSnapshot.itens.filter(item => item.classeFinal === "A" && item.materialId && !existing.has(item.materialId)).map(item => createSupplyPlan({ id:id("sup"), obraId, snapshot:activeSnapshot, item, tasks, movements:data.movEstoque || [], reservations:data.reservasEstoque || [], orders:data.pedidos || [], profile, calendar:settings.calendario, actor:currentUser, now:now() }));
    if (!created.length) return showToast?.("Não há novos insumos A com vínculo material confirmado para planejar.", "warn");
    const milestones = created.flatMap(planItem => planItem.etapas.map(stage => ({ id:id("marco"), obraId, planoSuprimentoId:planItem.id, nome:`${planItem.codigo || planItem.descricao} · ${stage.nome}`, tipo:"suprimento", dataBaseline:stage.dataSugeridaFim, dataAtual:"", dataPrevista:stage.dataSugeridaFim, dataRealizada:"", status:"nao_iniciado", predecessoras:[], tarefaIds:planItem.tarefaIds, materialIds:[planItem.materialId], origem:"plano_suprimento", version:1, createdAt:now(), createdById:currentUser?.id || "", createdBy:currentUser?.nome || "" })));
    update({ ...data, planosSuprimento:[...(data.planosSuprimento || []), ...created], marcosSuprimento:[...(data.marcosSuprimento || []), ...milestones] });
    showToast?.(`${created.length} plano(s) e ${milestones.length} marco(s) gerados sem alterar a baseline do cronograma.`);
  };
  const updateSettings = field => event => update({ ...data, suprimentosConfig:{ ...(data.suprimentosConfig || {}), abc:{ ...settings.abc, [field]:Number(event.target.value || 0) } } });
  const nav = [["visao","Visão geral"],["insumos","Insumos A"],["gantt","Gantt de suprimentos"],["detalhe","Detalhe"],["config","Configuração"]];
  const selectedSnapshot = snapshots[0];

  return <Shell>
    <div style={{ display:"flex", flexWrap:"wrap", justifyContent:"space-between", alignItems:"end", gap:12, marginBottom:12 }}>
      <div><p style={{ margin:0, color:"#8a6d1d", fontSize:10, fontWeight:900, letterSpacing:.8 }}>PLANEJAMENTO / SUPRIMENTOS ESTRATÉGICOS</p><h1 style={{ margin:"4px 0 0", fontSize:22, letterSpacing:-.4 }}>Marcos de obra e Curva A</h1><p style={{ margin:"5px 0 0", color:"#667085", fontSize:11.5 }}>Orçamento → Curva ABC → tarefas consumidoras → necessidade → contratação. Sugestões nunca substituem compromissos.</p></div>
      {!obraIdFixo && <label style={{ fontSize:10, fontWeight:800 }}>OBRA<br/><select value={obraId} onChange={event => { setObraId(event.target.value); setSelectedId(""); }} style={{ minWidth:220, marginTop:4, minHeight:34, border:"1px solid #c8d0d8", borderRadius:6, padding:"0 8px", background:"#fff" }}>{works.map(work => <option key={work.id} value={work.id}>{work.name}</option>)}</select></label>}
    </div>
    {!planning.budget && <Panel style={{ padding:16, borderLeft:"4px solid #b54708", marginBottom:12 }}><b style={{ fontSize:12 }}>Não há orçamento disponível para esta obra.</b><p style={{ margin:"4px 0 0", fontSize:11, color:"#667085" }}>O planejamento pode existir com rascunho, mas a Curva ABC somente usa uma versão explícita do orçamento.</p></Panel>}
    {planning.budget && <Panel style={{ padding:"10px 12px", marginBottom:12, display:"flex", justifyContent:"space-between", alignItems:"center", gap:10, flexWrap:"wrap" }}><span style={{ fontSize:11 }}>Fonte: <b>{planning.source === "baseline" ? "baseline aprovada" : "orçamento de planejamento (rascunho)"}</b> · {planning.budget.nome || planning.budget.codigo || "Orçamento sem nome"}</span><span style={{ fontSize:10, color:"#667085" }}>Versão {planning.budget.versionNumber || 1} · {demands.length} insumo(s) analítico(s) identificado(s)</span></Panel>}
    <div style={{ display:"flex", gap:4, overflowX:"auto", borderBottom:"1px solid #d7dde2", marginBottom:14 }}>{nav.map(([key,label]) => <button key={key} onClick={() => setView(key)} style={{ whiteSpace:"nowrap", border:0, borderBottom:`2px solid ${view === key ? "#b7941e" : "transparent"}`, background:"transparent", padding:"9px 11px", fontSize:11, fontWeight:view === key ? 900 : 700, color:view === key ? "#3a3211" : "#667085", cursor:"pointer" }}>{label}</button>)}</div>
    {view === "visao" && <>
      <div style={{ display:"flex", gap:8, flexWrap:"wrap", marginBottom:12 }}><Button onClick={generateProposal} disabled={!planning.budget}>Gerar proposta ABC</Button>{selectedSnapshot?.status === "proposta" && <Button secondary={!canApprove(currentUser)} onClick={() => approve(selectedSnapshot)} disabled={!canApprove(currentUser)}>Aprovar proposta</Button>}<select value={profileId} onChange={event => setProfileId(event.target.value)} style={{ minHeight:34, border:"1px solid #c8d0d8", borderRadius:6, padding:"0 8px", background:"#fff", fontSize:11 }}>{profiles.map(profile => <option key={profile.id} value={profile.id}>{profile.nome} · {profile.total} dias úteis</option>)}</select><Button onClick={generatePlans} disabled={!activeSnapshot}>Gerar planos dos itens A</Button></div>
      <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(155px,1fr))", gap:8 }}>{[["Valor Curva A",money(summary.value),"#344054"],["Itens A",supplyPlans.length,"#344054"],["Risco crítico/alto",`${summary.risk.critico || 0} / ${summary.risk.alto || 0}`,"#b54708"],["Sem pedido",summary.withoutOrder,"#b54708"],["Vínculos pendentes",summary.pending,"#b54708"]].map(([label,value,color]) => <Panel key={label} style={{ padding:12 }}><p style={{ margin:0, fontSize:9, fontWeight:900, color:"#667085", textTransform:"uppercase" }}>{label}</p><b style={{ display:"block", marginTop:7, fontSize:20, color }}>{value}</b></Panel>)}</div>
      <Panel style={{ marginTop:12, padding:14 }}><b style={{ fontSize:12 }}>Próximos marcos de suprimento</b>{!supplyPlans.length ? <p style={{ color:"#667085", fontSize:11 }}>Aprove a Curva ABC e gere os planos dos itens A. Nenhum dado operacional será alterado.</p> : supplyPlans.slice().sort((a,b) => String(a.dataInicioSugerido).localeCompare(String(b.dataInicioSugerido))).slice(0,6).map(item => <div key={item.id} style={{ display:"grid", gridTemplateColumns:"1fr auto", gap:12, padding:"10px 0", borderTop:"1px solid #e6e9ec" }}><span><b style={{ fontSize:11 }}>{item.codigo || "Sem código"} · {item.descricao}</b><small style={{ display:"block", color:"#667085", marginTop:2 }}>Início recomendado {date(item.dataInicioSugerido)} · necessidade {date(item.dataNecessidade)}</small></span><b style={{ fontSize:10, color:colorRisk(item.risco), textTransform:"uppercase" }}>{item.risco}</b></div>)}</Panel>
    </>}
    {view === "insumos" && <Panel style={{ overflow:"auto" }}><table style={{ width:"100%", borderCollapse:"collapse", minWidth:1100, fontSize:10.5 }}><thead><tr style={{ background:"#f4f5f3", color:"#667085", textAlign:"left" }}>{["Código / insumo","Classe","Valor","Qtd.","Estoque livre","Pedido aberto","Comprar","Necessidade","Início recomendado","Compromisso","Folga","Risco"].map(label => <th key={label} style={{ padding:"9px 10px", fontSize:9, textTransform:"uppercase" }}>{label}</th>)}</tr></thead><tbody>{supplyPlans.map(item => <tr key={item.id} onClick={() => { setSelectedId(item.id); setView("detalhe"); }} style={{ cursor:"pointer", borderTop:"1px solid #e6e9ec" }}><td style={{ padding:10, maxWidth:200 }}><b>{item.codigo || "—"}</b><span style={{ display:"block", color:"#667085", marginTop:2 }}>{item.descricao}</span></td><td style={{ padding:10 }}>{(activeSnapshot?.itens || []).find(x=>x.materialId===item.materialId)?.classeFinanceira || "A"} / <b>A</b></td><td style={{ padding:10 }}>{money((activeSnapshot?.itens || []).find(x=>x.materialId===item.materialId)?.custoTotal)}</td><td style={{ padding:10 }}>{item.quantidadeNecessaria}</td><td style={{ padding:10 }}>{item.estoqueDisponivel}</td><td style={{ padding:10 }}>{item.quantidadePedidosAbertos}</td><td style={{ padding:10, fontWeight:900 }}>{item.quantidadeAComprar}</td><td style={{ padding:10 }}>{date(item.dataNecessidade)}</td><td style={{ padding:10 }}>{date(item.dataInicioSugerido)}</td><td style={{ padding:10 }}>{date(item.dataCompromissada)}</td><td style={{ padding:10 }}>{item.folgaDias ?? "—"}</td><td style={{ padding:10, color:colorRisk(item.risco), fontWeight:900, textTransform:"uppercase" }}>{item.risco}</td></tr>)}</tbody></table>{!supplyPlans.length && <p style={{ padding:18, color:"#667085", fontSize:11 }}>Ainda não há planos da Curva A aprovados para esta obra.</p>}</Panel>}
    {view === "gantt" && <Panel style={{ padding:14 }}><b style={{ fontSize:12 }}>Linha de suprimentos</b><p style={{ margin:"4px 0 12px", color:"#667085", fontSize:10.5 }}>Camada própria: os marcos abaixo não movem a WBS nem a baseline do cronograma.</p>{supplyPlans.map(item => <div key={item.id} style={{ borderTop:"1px solid #e6e9ec", padding:"10px 0" }}><div style={{ display:"flex", justifyContent:"space-between", gap:8 }}><b style={{ fontSize:11 }}>{item.codigo || "—"} · {item.descricao}</b><span style={{ fontSize:10, color:colorRisk(item.risco), fontWeight:900 }}>{item.risco.toUpperCase()}</span></div><div style={{ display:"flex", gap:4, overflowX:"auto", marginTop:8 }}>{item.etapas.map(stage => <div key={stage.id} style={{ minWidth:135, padding:8, background:"#f4f5f3", borderLeft:"3px solid #b7941e", borderRadius:4 }}><b style={{ fontSize:9.5 }}>{stage.nome}</b><span style={{ display:"block", fontSize:9, color:"#667085", marginTop:3 }}>{date(stage.dataSugeridaInicio)} → {date(stage.dataSugeridaFim)}</span></div>)}</div></div>)}{!supplyPlans.length && <p style={{ color:"#667085", fontSize:11 }}>Gere planos aprovados para visualizar os marcos.</p>}</Panel>}
    {view === "detalhe" && <Panel style={{ padding:14 }}>{!selected ? <p style={{ color:"#667085", fontSize:11 }}>Selecione um insumo na tabela para abrir sua memória de cálculo.</p> : <><div style={{ display:"flex", justifyContent:"space-between", gap:12, flexWrap:"wrap" }}><div><p style={{ margin:0, fontSize:10, color:"#8a6d1d", fontWeight:900 }}>PLANO DE SUPRIMENTO</p><h2 style={{ margin:"4px 0", fontSize:18 }}>{selected.codigo || "—"} · {selected.descricao}</h2><p style={{ margin:0, fontSize:11, color:"#667085" }}>Snapshot {selected.snapshotId} · versão {selected.version} · {selected.perfilLeadTimeNome}</p></div><b style={{ color:colorRisk(selected.risco), textTransform:"uppercase", fontSize:12 }}>{selected.risco}</b></div><div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(155px,1fr))", gap:8, marginTop:14 }}>{[["Necessidade",date(selected.dataNecessidade)],["Estoque livre",selected.estoqueDisponivel],["Pedidos abertos",selected.quantidadePedidosAbertos],["Saldo a comprar",selected.quantidadeAComprar],["Folga",selected.folgaDias == null ? "Sem previsão" : `${selected.folgaDias} dias úteis`]].map(([label,value]) => <div key={label} style={{ background:"#f4f5f3", padding:9, borderRadius:6 }}><small style={{ color:"#667085", fontSize:9 }}>{label}</small><b style={{ display:"block", marginTop:3, fontSize:12 }}>{value}</b></div>)}</div><h3 style={{ fontSize:12, margin:"16px 0 5px" }}>Memória da necessidade</h3><p style={{ margin:0, fontSize:11, color:"#667085" }}>Regra: menor início entre tarefas consumidoras. Tarefas: {(selected.memoriaNecessidade?.tarefas || []).join(", ") || "vínculo pendente"}.</p><h3 style={{ fontSize:12, margin:"16px 0 5px" }}>Marcos sugeridos</h3>{selected.etapas.map(stage => <div key={stage.id} style={{ display:"grid", gridTemplateColumns:"1fr auto", borderTop:"1px solid #e6e9ec", padding:"9px 0", gap:10 }}><span><b style={{ fontSize:11 }}>{stage.nome}</b><small style={{ display:"block", color:"#667085" }}>{stage.duracaoDias} dias úteis · sugestão {date(stage.dataSugeridaInicio)} a {date(stage.dataSugeridaFim)}</small></span><span style={{ fontSize:10, color:"#667085" }}>{stage.dataCompromissada ? `Compromisso ${date(stage.dataCompromissada)}` : "Sem compromisso"}</span></div>)}<h3 style={{ fontSize:12, margin:"16px 0 5px" }}>Risco e causa</h3><p style={{ margin:0, fontSize:11, color:colorRisk(selected.risco) }}>{selected.causas?.length ? selected.causas.join(" · ") : "Sem bloqueio identificado pela regra determinística."}</p></>}</Panel>}
    {view === "config" && <Panel style={{ padding:14, maxWidth:760 }}><h2 style={{ margin:0, fontSize:15 }}>Parâmetros por obra</h2><p style={{ color:"#667085", fontSize:11, lineHeight:1.5 }}>Alterar estes parâmetros não muda snapshots aprovados, pedidos ou compromissos existentes; a próxima Curva ABC será uma proposta nova.</p><div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))", gap:10 }}><label style={{ fontSize:10, fontWeight:800 }}>LIMITE CLASSE A (%)<input type="number" min="1" max="94" value={settings.abc.limiteA} onChange={updateSettings("limiteA")} style={{ display:"block", boxSizing:"border-box", marginTop:4, width:"100%", height:34, padding:"0 8px", border:"1px solid #c8d0d8", borderRadius:6 }}/></label><label style={{ fontSize:10, fontWeight:800 }}>LIMITE CLASSE B (%)<input type="number" min="2" max="100" value={settings.abc.limiteB} onChange={updateSettings("limiteB")} style={{ display:"block", boxSizing:"border-box", marginTop:4, width:"100%", height:34, padding:"0 8px", border:"1px solid #c8d0d8", borderRadius:6 }}/></label></div><h3 style={{ fontSize:12, margin:"18px 0 7px" }}>Perfis iniciais de lead time</h3>{profiles.map(profile => <div key={profile.id} style={{ padding:"8px 0", borderTop:"1px solid #e6e9ec", fontSize:11 }}><b>{profile.nome}</b><span style={{ color:"#667085" }}> · engenharia {profile.engenharia} + compra {profile.compra} + fornecimento {profile.fornecimento} + logística {profile.logistica} + buffer {profile.buffer} = {profile.total} dias úteis</span></div>)}<p style={{ marginTop:14, color:"#667085", fontSize:10.5 }}>Os perfis são parâmetros editáveis na base de dados; o módulo os usa para sugestão e mantém data sugerida, compromisso, previsão e realizado separados.</p></Panel>}
  </Shell>;
}
