-- Recuperação de bases SINAPI importadas antes do suporte analítico.
-- Execute uma vez no SQL Editor do Supabase. É idempotente e não apaga
-- orçamentos, bases existentes ou seus vínculos.

create extension if not exists pg_trgm;

create table if not exists public.budget_reference_inputs (
  id bigint generated by default as identity primary key,
  base_id uuid not null references public.budget_reference_bases(id) on delete cascade,
  company_id text not null,
  source text not null check (source in ('SINAPI', 'ORSE')),
  code text not null,
  description text not null,
  unit text not null default 'UN',
  classification text not null default '',
  price_des numeric(18, 6) not null default 0,
  price_not numeric(18, 6) not null default 0,
  search_text text not null default '',
  created_at timestamptz not null default now(),
  unique (base_id, source, code)
);

create table if not exists public.budget_reference_components (
  id bigint generated by default as identity primary key,
  base_id uuid not null references public.budget_reference_bases(id) on delete cascade,
  company_id text not null,
  source text not null check (source in ('SINAPI', 'ORSE')),
  composition_code text not null,
  item_type text not null check (item_type in ('INSUMO', 'COMPOSICAO')),
  item_code text not null,
  description text not null default '',
  unit text not null default 'UN',
  coefficient numeric(24, 10) not null default 0,
  situation text not null default '',
  created_at timestamptz not null default now(),
  unique (base_id, source, composition_code, item_type, item_code)
);

create index if not exists budget_reference_inputs_base_idx
  on public.budget_reference_inputs (base_id, code);
create index if not exists budget_reference_inputs_search_idx
  on public.budget_reference_inputs using gin (search_text gin_trgm_ops);
create index if not exists budget_reference_components_composition_idx
  on public.budget_reference_components (base_id, composition_code);

alter table public.budget_reference_inputs enable row level security;
alter table public.budget_reference_components enable row level security;

drop policy if exists "allow_all" on public.budget_reference_inputs;
drop policy if exists "allow_all" on public.budget_reference_components;

notify pgrst, 'reload schema';
