-- ═══════════════════════════════════════════════════════════════════
-- ArcD Ponto PRO — schema
--
-- Agora o navegador NÃO fala com o banco. Quem fala é /api/data, no
-- servidor, usando a service_role key (que ignora RLS por natureza).
--
-- Logo, a política aqui é a mais restritiva possível: NINGUÉM entra
-- pelo cliente. Se alguém roubar a anon key do bundle, não consegue
-- ler uma linha.
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.company_app_data (
  company_id  text        not null,
  key         text        not null,
  value       jsonb       not null,
  updated_at  timestamptz not null default now(),
  updated_by  uuid,
  primary key (company_id, key)
);

alter table public.company_app_data enable row level security;

-- Apaga a política insegura do SETUP antigo, se você chegou a rodá-la
drop policy if exists "allow_all" on public.company_app_data;

-- NENHUMA política de acesso para anon/authenticated.
-- Sem política = acesso negado por padrão. É exatamente o que queremos:
-- o único caminho até estes dados é a função serverless, que usa a
-- service_role key e confere o PIN antes de devolver qualquer coisa.

-- Linha inicial (o app preenche no primeiro acesso)
insert into public.company_app_data (company_id, key, value)
values ('arcd', 'arced_ponto_v1', '{}'::jsonb)
on conflict (company_id, key) do nothing;

-- ═══════════════════════════════════════════════════════════════════
-- Bases de referência do orçamento
--
-- As milhares de composições não entram no JSON principal. Cada base tem
-- metadados próprios e seus itens ficam normalizados, permitindo pesquisar
-- SINAPI e ORSE sem reenviar todo o aplicativo a cada salvamento.
-- ═══════════════════════════════════════════════════════════════════

create extension if not exists pg_trgm;

create table if not exists public.budget_reference_bases (
  id            uuid        primary key default gen_random_uuid(),
  company_id    text        not null,
  source        text        not null check (source in ('SINAPI', 'ORSE')),
  competence    text        not null check (competence ~ '^\d{4}-\d{2}$'),
  uf            text,
  desonerado    boolean,
  file_name     text,
  file_hash     text,
  mode          text        not null default 'uploaded',
  status        text        not null default 'processing',
  item_count    integer     not null default 0,
  created_at    timestamptz not null default now(),
  created_by    text
);

alter table public.budget_reference_bases
  alter column created_by type text using created_by::text;

create table if not exists public.budget_reference_items (
  id            bigint generated by default as identity primary key,
  base_id       uuid        not null references public.budget_reference_bases(id) on delete cascade,
  company_id    text        not null,
  source        text        not null check (source in ('SINAPI', 'ORSE')),
  code          text        not null,
  description   text        not null,
  unit          text        not null default 'UN',
  price_des     numeric(18, 6) not null default 0,
  price_not     numeric(18, 6) not null default 0,
  search_text   text        not null default '',
  detail_url    text,
  created_at    timestamptz not null default now(),
  unique (base_id, source, code)
);

-- Preços unitários dos insumos. Eles ficam separados das composições porque
-- os códigos podem coincidir e porque a Curva ABC precisa do preço elementar.
create table if not exists public.budget_reference_inputs (
  id              bigint generated by default as identity primary key,
  base_id         uuid        not null references public.budget_reference_bases(id) on delete cascade,
  company_id      text        not null,
  source          text        not null check (source in ('SINAPI', 'ORSE')),
  code            text        not null,
  description     text        not null,
  unit            text        not null default 'UN',
  classification  text        not null default '',
  price_des       numeric(18, 6) not null default 0,
  price_not       numeric(18, 6) not null default 0,
  search_text     text        not null default '',
  created_at      timestamptz not null default now(),
  unique (base_id, source, code)
);

-- Relação analítica: uma composição contém insumos e/ou outras composições.
create table if not exists public.budget_reference_components (
  id                bigint generated by default as identity primary key,
  base_id           uuid        not null references public.budget_reference_bases(id) on delete cascade,
  company_id        text        not null,
  source            text        not null check (source in ('SINAPI', 'ORSE')),
  composition_code  text        not null,
  item_type         text        not null check (item_type in ('INSUMO', 'COMPOSICAO')),
  item_code         text        not null,
  description       text        not null default '',
  unit              text        not null default 'UN',
  coefficient       numeric(24, 10) not null default 0,
  situation         text        not null default '',
  created_at        timestamptz not null default now(),
  unique (base_id, source, composition_code, item_type, item_code)
);

create index if not exists budget_reference_bases_company_idx
  on public.budget_reference_bases (company_id, source, competence desc);

create index if not exists budget_reference_items_base_idx
  on public.budget_reference_items (base_id, code);

create index if not exists budget_reference_items_search_idx
  on public.budget_reference_items using gin (search_text gin_trgm_ops);

create index if not exists budget_reference_inputs_base_idx
  on public.budget_reference_inputs (base_id, code);

create index if not exists budget_reference_inputs_search_idx
  on public.budget_reference_inputs using gin (search_text gin_trgm_ops);

create index if not exists budget_reference_components_composition_idx
  on public.budget_reference_components (base_id, composition_code);

alter table public.budget_reference_bases enable row level security;
alter table public.budget_reference_items enable row level security;
alter table public.budget_reference_inputs enable row level security;
alter table public.budget_reference_components enable row level security;

drop policy if exists "allow_all" on public.budget_reference_bases;
drop policy if exists "allow_all" on public.budget_reference_items;
drop policy if exists "allow_all" on public.budget_reference_inputs;
drop policy if exists "allow_all" on public.budget_reference_components;

-- Sem políticas para anon/authenticated: somente as rotas serverless com
-- service_role e PIN validado acessam estas tabelas.

-- Força a Data API/PostgREST a reconhecer imediatamente as tabelas novas.
notify pgrst, 'reload schema';

-- Em bancos existentes, prefira executar o arquivo menor e idempotente
-- MIGRACAO_REFERENCIAS_ANALITICAS.sql. Depois reenvie a base SINAPI para
-- preencher os insumos e as relações analíticas das composições.
