import { calculateABC, calculateBudget, projectBudgetABC, projectBudgetExport, getActiveBudgetBaseline, getPlanningBudget, createBudgetRevision, adoptBudgetBaseline, budgetIsImmutable } from "./calculations";
const budget={id:"o1",bdi:20,areaM2:100,etapas:[{id:"e1",parentId:""}],itens:[{id:"i1",etapaId:"e1",quantidade:2,precoUnit:100},{id:"i2",etapaId:"e1",quantidade:1,precoUnit:100,bdi:10}]};
describe("motor canônico de orçamento",()=>{
 test("respeita BDI por item em totais e etapa",()=>{const c=calculateBudget(budget);expect(c.custoDireto).toBe(300);expect(c.valorBDI).toBe(50);expect(c.total).toBe(350);expect(c.etapas[0].total).toBe(350);});
 test("ABC conserva o total calculado",()=>{const abc=calculateABC(budget);expect(abc.totalComBDI).toBe(350);expect(abc.items.reduce((s,i)=>s+i.total,0)).toBe(350);});
 test("projeção ABC respeita BDI específico e agrupamento",()=>{const input={bdi:10,itens:[{id:"1",codigo:"A",unidade:"UN",quantidade:1,precoUnit:100,bdi:20},{id:"2",codigo:"A",unidade:"UN",quantidade:1,precoUnit:100,bdi:0}]};const grouped=projectBudgetABC(input);expect(grouped.itens).toHaveLength(1);expect(grouped.totalCD).toBe(200);expect(grouped.totalComBDI).toBe(220);expect(grouped.itens[0].total).toBe(220);expect(projectBudgetABC(input,{group:false}).itens).toHaveLength(2);});
 test("projeção de exportação preserva os mesmos centavos e BDI do motor",()=>{const motor=calculateBudget(budget),exportacao=projectBudgetExport(budget);expect(exportacao.totalCentavos).toBe(motor.totalCentavos);expect(exportacao.rows.map(item=>item.totalCentavos)).toEqual(motor.items.map(item=>item.totalCentavos));expect(exportacao.rows.map(item=>item.bdi)).toEqual([20,10]);expect(exportacao.rows.map(item=>item.precoUnitario)).toEqual([120,110]);});
 test("não escolhe orçamento sem baseline explícita",()=>{expect(getActiveBudgetBaseline({orcamentos:[budget]},"obra").case).toBe("baseline_ausente");});
 test("planejamento usa rascunho sem transformá-lo em baseline",()=>{const draft={...budget,obraId:"obra",versionStatus:"rascunho"};const data={orcamentos:[draft],budgetBaselines:[]};expect(getPlanningBudget(data,"obra").budget.id).toBe("o1");expect(getPlanningBudget(data,"obra").source).toBe("rascunho");expect(getActiveBudgetBaseline(data,"obra").budget).toBeNull();});
 test("vínculo operacional escolhe o rascunho mais recente da obra",()=>{const antigo={...budget,id:"o1",obraId:"obra",versionStatus:"rascunho",updatedAt:"2026-06-01"},novo={...budget,id:"o2",obraId:"obra",versionStatus:"rascunho",updatedAt:"2026-07-29"};const outraObra={...budget,id:"o3",obraId:"outra",updatedAt:"2026-07-30"};const contexto=getPlanningBudget({orcamentos:[antigo,outraObra,novo],budgetBaselines:[]},"obra");expect(contexto.budget.id).toBe("o2");expect(contexto.source).toBe("rascunho");expect(getActiveBudgetBaseline({orcamentos:[antigo,novo]},"obra").budget).toBeNull();});
 test("planejamento conserva a versão explicitamente vinculada",()=>{const antigo={...budget,id:"o1",obraId:"obra",updatedAt:"2026-01-01"},novo={...budget,id:"o2",obraId:"obra",updatedAt:"2026-07-01"};expect(getPlanningBudget({orcamentos:[antigo,novo]}, "obra", {budgetId:"o1"}).budget.id).toBe("o1");});
 test("aprovação adota baseline única e bloqueia a versão",()=>{const original={...budget,obraId:"obra",versionId:"v1",versionNumber:1};const r=adoptBudgetBaseline({orcamentos:[original],budgetBaselines:[]},"o1",{id:"b1",now:"2026-07-25T10:00:00Z",actorId:"u1"});expect(r.ok).toBe(true);expect(budgetIsImmutable(r.budget)).toBe(true);expect(getActiveBudgetBaseline(r.data,"obra").budget.id).toBe("o1");});
 test("revisão parte da aprovada sem alterar sua identidade",()=>{const revisao=createBudgetRevision({...budget,versionId:"v1",versionNumber:1,versionStatus:"aprovado"},{id:"o2",versionId:"v2",now:"2026-07-25T10:00:00Z"});expect(revisao.revisionOf).toBe("v1");expect(revisao.versionNumber).toBe(2);expect(budgetIsImmutable(revisao)).toBe(false);});
});
