import { useMemo,useState } from "react";
import { Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { Building2,CalendarDays,FileText,Home,Plus,Search,Tag,Users,X } from "lucide-react";
import {
  DEVELOPMENT_STATUSES,PROPERTY_NATURES,PROPERTY_TYPES,UNIT_STATUSES,
  createPropertySale,createReservation,releaseExpiredReservations,selectRealEstateDashboard,updateUnitWithAudit,
} from "./real-estate.js";
import "./real-estate.css";

const COLORS=["#2563eb","#16a34a","#d4af37","#ea580c","#7c3aed","#dc2626","#64748b"];
const id=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const money=value=>Number(value||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const label=value=>String(value||"").replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase());
const date=value=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString("pt-BR"):"—";
const number=value=>Number(value||0);
const Field=({label:fieldLabel,children,wide=false})=><label className={wide?"re-field re-field--wide":"re-field"}><span>{fieldLabel}</span>{children}</label>;
const Input=props=><input {...props}/>;
const Select=({options,...props})=><select {...props}>{options.map(option=><option key={typeof option==="string"?option:option.value} value={typeof option==="string"?option:option.value}>{typeof option==="string"?label(option):option.label}</option>)}</select>;
const Empty=({children})=><div className="re-empty">{children}</div>;

function Dialog({title,onClose,onSubmit,children,submit="Salvar"}){
  return <div className="re-dialog-backdrop" role="presentation"><form className="re-dialog" onSubmit={event=>{event.preventDefault();onSubmit();}}><header><h3>{title}</h3><button type="button" onClick={onClose} aria-label="Fechar"><X size={17}/></button></header><div className="re-dialog-grid">{children}</div><footer><button type="button" className="re-btn re-btn--ghost" onClick={onClose}>Cancelar</button><button className="re-btn re-btn--primary" type="submit">{submit}</button></footer></form></div>;
}

const assetName=(commercial,unitId,propertyId)=>{
  const unit=(commercial.unidadesImobiliarias||[]).find(item=>item.id===unitId);
  if(unit){const dev=(commercial.empreendimentos||[]).find(item=>item.id===unit.empreendimentoId);return `${dev?.nome||"Empreendimento"} · ${unit.codigo||unit.numero}`;}
  return (commercial.imoveisAvulsos||[]).find(item=>item.id===propertyId)?.titulo||"Imóvel";
};

export function RealEstateCommercial({section,commercial,appData,currentUser,onSave,onLegacyNavigate}){
  const clean=useMemo(()=>releaseExpiredReservations(commercial),[commercial]);
  const [modal,setModal]=useState(null);const [form,setForm]=useState({});const [query,setQuery]=useState("");
  const [filters,setFilters]=useState({empreendimentoId:"",status:"",tipo:"",corretorId:""});
  const dashboard=useMemo(()=>selectRealEstateDashboard(clean,filters),[clean,filters]);
  const obras=appData.obras||[],users=(appData.usuarios||[]).filter(user=>user.active!==false);
  const set=(key,value)=>setForm(current=>({...current,[key]:value}));
  const saveCollection=async(collection,record,message)=>{
    const rows=clean[collection]||[];const next=rows.some(item=>item.id===record.id)?rows.map(item=>item.id===record.id?record:item):[...rows,record];
    const ok=await onSave({...clean,[collection]:next},message);if(ok)setModal(null);
  };
  const open=(type,record={})=>{setForm({...record});setModal(type);};
  const created=()=>new Date().toISOString();

  const saveDevelopment=()=>saveCollection("empreendimentos",{
    ...form,id:form.id||id(),codigo:form.codigo||`EMP-${String(clean.empreendimentos.length+1).padStart(3,"0")}`,
    vgvTotal:number(form.vgvTotal),quantidadeUnidades:number(form.quantidadeUnidades),comissaoPadrao:number(form.comissaoPadrao),
    percentualFisico:number(form.percentualFisico),status:form.status||"estudo",documentos:form.documentos||[],imagens:form.imagens||[],videos:form.videos||[],
    createdAt:form.createdAt||created(),updatedAt:created(),
  },"Empreendimento salvo.");
  const saveUnit=async()=>{
    if(!form.empreendimentoId||!form.codigo)return;
    const previous=clean.unidadesImobiliarias.find(item=>item.id===form.id);
    const record=updateUnitWithAudit({previous,actor:currentUser,unit:{...form,id:form.id||id(),status:form.status||"disponivel",valorTabela:number(form.valorTabela),valorMinimo:number(form.valorMinimo),areaPrivativa:number(form.areaPrivativa),areaTotal:number(form.areaTotal),comissaoPct:number(form.comissaoPct),quartos:number(form.quartos),suites:number(form.suites),banheiros:number(form.banheiros),vagas:number(form.vagas),documentos:form.documentos||[],imagens:form.imagens||[]}});
    await saveCollection("unidadesImobiliarias",record,"Unidade salva com histórico de preço e status.");
  };
  const saveProperty=()=>saveCollection("imoveisAvulsos",{
    ...form,id:form.id||id(),codigo:form.codigo||`IMO-${String(clean.imoveisAvulsos.length+1).padStart(3,"0")}`,
    tipo:form.tipo||"casa",natureza:form.natureza||"proprio",status:form.status||"disponivel",valorVenda:number(form.valorVenda),valorMinimo:number(form.valorMinimo),comissaoPct:number(form.comissaoPct),areaConstruida:number(form.areaConstruida),areaTerreno:number(form.areaTerreno),quartos:number(form.quartos),suites:number(form.suites),banheiros:number(form.banheiros),vagas:number(form.vagas),documentos:form.documentos||[],imagens:form.imagens||[],videos:form.videos||[],createdAt:form.createdAt||created(),updatedAt:created(),
  },"Imóvel salvo.");
  const saveBroker=()=>saveCollection("corretores",{...form,id:form.id||id(),tipo:form.tipo||"interno",comissaoPadrao:number(form.comissaoPadrao),ativo:form.ativo!==false},"Corretor salvo.");
  const saveReservation=async()=>{try{const next=createReservation({commercial:clean,id:form.id||id(),actor:currentUser,reservation:{...form,valor:number(form.valor)}});const ok=await onSave(next,"Reserva criada e disponibilidade atualizada.");if(ok)setModal(null);}catch(error){window.alert(error.message);}};
  const saveSale=async()=>{try{const asset=form.asset||"";const [type,assetId]=asset.split(":");const next=createPropertySale({commercial:clean,id:form.id||id(),actor:currentUser,sale:{...form,unidadeId:type==="unit"?assetId:"",imovelId:type==="property"?assetId:"",valor:number(form.valor),valorRecebido:number(form.valorRecebido),comissaoPct:number(form.comissaoPct),aprovadoAbaixoMinimo:form.aprovadoAbaixoMinimo===true}});const ok=await onSave(next,"Venda registrada e unidade retirada da disponibilidade.");if(ok)setModal(null);}catch(error){window.alert(error.message);}};
  const saveVisit=()=>saveCollection("visitasImobiliarias",{...form,id:form.id||id(),status:form.status||"agendada",createdAt:form.createdAt||created()},"Visita salva.");

  const unitRows=clean.unidadesImobiliarias.filter(item=>[item.codigo,item.numero,item.tipologia].join(" ").toLowerCase().includes(query.toLowerCase()));
  const propertyRows=clean.imoveisAvulsos.filter(item=>[item.codigo,item.titulo,item.endereco].join(" ").toLowerCase().includes(query.toLowerCase()));
  const groupedUnits=clean.empreendimentos.map(development=>({development,units:unitRows.filter(unit=>unit.empreendimentoId===development.id)})).filter(group=>group.units.length);

  const Header=({eyebrow,title,description,action})=><header className="re-page-header"><div><span>{eyebrow}</span><h2>{title}</h2><p>{description}</p></div>{action}</header>;
  const SearchBar=()=> <div className="re-search"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar por código, nome, unidade ou endereço"/></div>;
  let content=null;

  if(section==="overview"){
    const m=dashboard.metrics;
    const unitStatus=UNIT_STATUSES.map(status=>({name:label(status),value:dashboard.units.filter(unit=>unit.status===status).length})).filter(item=>item.value);
    const vgvByDevelopment=dashboard.developments.map(dev=>({name:dev.nome,vgv:dashboard.units.filter(unit=>unit.empreendimentoId===dev.id).reduce((sum,unit)=>sum+number(unit.valorTabela),0)}));
    const salesByMonth=Object.values(dashboard.sales.reduce((map,sale)=>{const month=String(sale.fechadaEm||sale.createdAt||"").slice(0,7)||"Sem data";map[month]??={month,value:0};map[month].value+=number(sale.valor);return map;},{}));
    const leadOrigins=Object.values((clean.leads||[]).reduce((map,lead)=>{const origin=lead.origem||"Não informada";map[origin]??={name:label(origin),value:0};map[origin].value++;return map;},{}));
    content=<><Header eyebrow="Comercial imobiliário" title="Visão geral" description="Disponibilidade, VGV, vendas, reservas e recebimentos em uma única leitura."/>
      <div className="re-filters"><Select value={filters.empreendimentoId} onChange={event=>setFilters({...filters,empreendimentoId:event.target.value})} options={[{value:"",label:"Todos os empreendimentos"},...clean.empreendimentos.map(item=>({value:item.id,label:item.nome}))]}/><Select value={filters.status} onChange={event=>setFilters({...filters,status:event.target.value})} options={[{value:"",label:"Todos os status"},...UNIT_STATUSES]}/><Select value={filters.corretorId} onChange={event=>setFilters({...filters,corretorId:event.target.value})} options={[{value:"",label:"Todos os corretores"},...clean.corretores.map(item=>({value:item.id,label:item.nome}))]}/></div>
      <div className="re-kpis">{[["VGV disponível",m.vgvAvailable],["VGV vendido",m.vgvSold],["VGV reservado",m.vgvReserved],["Em negociação",m.vgvNegotiation],["Recebido",m.received],["Saldo a receber",m.receivable],["Unidades disponíveis",m.availableUnits],["Reservadas",m.reservedUnits],["Vendidas",m.soldUnits],["Leads ativos",m.activeLeads],["Propostas abertas",m.openProposals],["Ticket médio",m.averageTicket],["Conversão",`${m.conversionRate.toFixed(1)}%`],["Comissão prevista",m.commissionExpected],["Comissão paga",m.commissionPaid]].map(([name,value])=><article key={name}><span>{name}</span><strong>{typeof value==="number"&&(name.includes("VGV")||name.includes("Receb")||name.includes("Saldo")||name.includes("Ticket")||name.includes("Comissão")||name.includes("negociação"))?money(value):value}</strong></article>)}</div>
      <div className="re-charts"><article><h3>Vendas por mês</h3><ResponsiveContainer width="100%" height={210}><BarChart data={salesByMonth}><CartesianGrid vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={value=>`${Math.round(value/1000)}k`}/><Tooltip formatter={money}/><Bar dataKey="value" fill="#d4af37"/></BarChart></ResponsiveContainer></article><article><h3>VGV por empreendimento</h3><ResponsiveContainer width="100%" height={210}><BarChart data={vgvByDevelopment}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis tickFormatter={value=>`${Math.round(value/1000)}k`}/><Tooltip formatter={money}/><Bar dataKey="vgv" fill="#2563eb"/></BarChart></ResponsiveContainer></article><article><h3>Unidades por status</h3><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={unitStatus} dataKey="value" nameKey="name" innerRadius={45} outerRadius={78}>{unitStatus.map((_,index)=><Cell key={index} fill={COLORS[index%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></article><article><h3>Origem dos leads</h3><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={leadOrigins} dataKey="value" nameKey="name" outerRadius={78}>{leadOrigins.map((_,index)=><Cell key={index} fill={COLORS[index%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></article></div></>;
  }else if(section==="developments"){
    content=<><Header eyebrow="Portfólio próprio" title="Empreendimentos" description="Dados comerciais conectados às obras, sem duplicar custos ou avanço físico." action={<button className="re-btn re-btn--primary" onClick={()=>open("development",{})}><Plus size={15}/> Empreendimento</button>}/><div className="re-card-grid">{clean.empreendimentos.map(dev=>{const units=clean.unidadesImobiliarias.filter(unit=>unit.empreendimentoId===dev.id);const work=obras.find(item=>item.id===dev.obraId);return <article className="re-development-card" key={dev.id}><header><div><span>{dev.codigo||"SEM CÓDIGO"}</span><h3>{dev.nome}</h3></div><b>{label(dev.status)}</b></header><p>{dev.endereco||"Endereço não informado"}</p><div className="re-mini-kpis"><span>VGV <strong>{money(dev.vgvTotal||units.reduce((sum,item)=>sum+number(item.valorTabela),0))}</strong></span><span>Unidades <strong>{units.length}</strong></span><span>Disponíveis <strong>{units.filter(item=>item.status==="disponivel").length}</strong></span></div>{work&&<div className="re-work-link"><Building2 size={14}/><span><b>{work.name}</b><small>Obra vinculada · {work.status||"ativa"} · contrato {money(work.contractValue)}</small></span></div>}<footer><button className="re-btn re-btn--ghost" onClick={()=>open("development",dev)}>Editar</button></footer></article>;})}{!clean.empreendimentos.length&&<Empty>Nenhum empreendimento cadastrado.</Empty>}</div></>;
  }else if(section==="units"){
    content=<><Header eyebrow="Espelho de vendas" title="Unidades" description="Disponibilidade por empreendimento, torre, pavimento e status." action={<button className="re-btn re-btn--primary" onClick={()=>open("unit",{})}><Plus size={15}/> Unidade</button>}/><SearchBar/>{groupedUnits.map(({development,units})=><section className="re-unit-group" key={development.id}><header><h3>{development.nome}</h3><span>{units.length} unidade(s)</span></header><div className="re-unit-grid">{units.map(unit=><button key={unit.id} className={`re-unit re-unit--${unit.status}`} onClick={()=>open("unit",unit)}><span>{unit.bloco||unit.torre||""} {unit.pavimento?`· ${unit.pavimento}º`:""}</span><strong>{unit.codigo||unit.numero}</strong><small>{unit.tipologia||"Tipologia não informada"} · {unit.areaPrivativa||0} m²</small><b>{money(unit.valorTabela)}</b><em>{label(unit.status)}</em></button>)}</div></section>)}{!groupedUnits.length&&<Empty>Nenhuma unidade encontrada.</Empty>}</>;
  }else if(section==="properties"){
    content=<><Header eyebrow="Imóveis prontos e de terceiros" title="Imóveis avulsos" description="Captações próprias, parceiros, terceiros, permutas e exclusividades." action={<button className="re-btn re-btn--primary" onClick={()=>open("property",{})}><Plus size={15}/> Imóvel</button>}/><SearchBar/><div className="re-card-grid">{propertyRows.map(item=><article className="re-property-card" key={item.id}><div className="re-property-image">{item.imagens?.[0]?.url?<img src={item.imagens[0].url} alt=""/>:<Home size={30}/>}</div><div><span>{item.codigo} · {label(item.natureza)}</span><h3>{item.titulo}</h3><p>{label(item.tipo)} · {item.quartos||0} quartos · {item.areaConstruida||item.areaTerreno||0} m²</p><strong>{money(item.valorVenda)}</strong><em>{label(item.status)}</em></div><button className="re-btn re-btn--ghost" onClick={()=>open("property",item)}>Editar</button></article>)}{!propertyRows.length&&<Empty>Nenhum imóvel encontrado.</Empty>}</div></>;
  }else if(section==="reservations"){
    content=<><Header eyebrow="Controle de disponibilidade" title="Reservas" description="Reservas vencidas liberam automaticamente a unidade e preservam o histórico." action={<button className="re-btn re-btn--primary" onClick={()=>open("reservation",{})}><Plus size={15}/> Reserva</button>}/><div className="re-table-wrap"><table><thead><tr><th>Imóvel</th><th>Cliente / lead</th><th>Corretor</th><th>Validade</th><th>Status</th><th>Valor</th></tr></thead><tbody>{clean.reservasImobiliarias.map(item=><tr key={item.id}><td>{assetName(clean,item.unidadeId,item.imovelId)}</td><td>{(clean.clientes||[]).find(client=>client.id===item.clienteId)?.nome||(clean.leads||[]).find(lead=>lead.id===item.leadId)?.nome||"—"}</td><td>{clean.corretores.find(broker=>broker.id===item.corretorId)?.nome||"—"}</td><td>{date(item.validade)}</td><td><span className={`re-status re-status--${item.status}`}>{label(item.status)}</span></td><td>{money(item.valor)}</td></tr>)}</tbody></table>{!clean.reservasImobiliarias.length&&<Empty>Nenhuma reserva.</Empty>}</div></>;
  }else if(section==="sales"){
    content=<><Header eyebrow="Fechamentos imobiliários" title="Vendas" description="Contratos, recebimentos, saldo e comissão vinculados ao imóvel vendido." action={<button className="re-btn re-btn--primary" onClick={()=>open("sale",{})}><Plus size={15}/> Venda</button>}/><div className="re-table-wrap"><table><thead><tr><th>Imóvel</th><th>Cliente</th><th>Corretor</th><th>Data</th><th>Venda</th><th>Recebido</th><th>Saldo</th><th>Comissão</th></tr></thead><tbody>{clean.vendasImobiliarias.map(item=><tr key={item.id}><td>{assetName(clean,item.unidadeId,item.imovelId)}</td><td>{(clean.clientes||[]).find(client=>client.id===item.clienteId)?.nome||(clean.leads||[]).find(lead=>lead.id===item.leadId)?.nome||"—"}</td><td>{clean.corretores.find(broker=>broker.id===item.corretorId)?.nome||"—"}</td><td>{date(item.fechadaEm)}</td><td>{money(item.valor)}</td><td>{money(item.valorRecebido)}</td><td>{money(number(item.valor)-number(item.valorRecebido))}</td><td>{money(item.comissaoPrevista)}</td></tr>)}</tbody></table>{!clean.vendasImobiliarias.length&&<Empty>Nenhuma venda imobiliária.</Empty>}</div></>;
  }else if(section==="visits"){
    content=<><Header eyebrow="Agenda comercial" title="Agenda e visitas" description="Visitas vinculadas a leads, corretores e imóveis." action={<button className="re-btn re-btn--primary" onClick={()=>open("visit",{})}><Plus size={15}/> Visita</button>}/><div className="re-list">{clean.visitasImobiliarias.map(item=><article key={item.id}><CalendarDays size={18}/><div><strong>{date(item.data)} · {item.hora||"Horário não informado"}</strong><p>{assetName(clean,item.unidadeId,item.imovelId)} · {(clean.leads||[]).find(lead=>lead.id===item.leadId)?.nome||"Lead não informado"}</p></div><span className={`re-status re-status--${item.status}`}>{label(item.status)}</span><button className="re-btn re-btn--ghost" onClick={()=>open("visit",item)}>Abrir</button></article>)}{!clean.visitasImobiliarias.length&&<Empty>Nenhuma visita agendada.</Empty>}</div></>;
  }else if(section==="brokers"){
    content=<><Header eyebrow="Rede de vendas" title="Corretores e parceiros" description="Equipe interna, CRECI, parceiros e comissão padrão." action={<button className="re-btn re-btn--primary" onClick={()=>open("broker",{})}><Plus size={15}/> Corretor</button>}/><div className="re-card-grid">{clean.corretores.map(item=><article className="re-broker-card" key={item.id}><Users size={22}/><div><h3>{item.nome}</h3><p>{item.tipo} · CRECI {item.creci||"não informado"}</p><strong>{item.comissaoPadrao}% de comissão padrão</strong></div><button className="re-btn re-btn--ghost" onClick={()=>open("broker",item)}>Editar</button></article>)}{!clean.corretores.length&&<Empty>Nenhum corretor cadastrado.</Empty>}</div></>;
  }else if(section==="documents"){
    const documents=[...clean.empreendimentos,...clean.unidadesImobiliarias,...clean.imoveisAvulsos,...clean.reservasImobiliarias,...clean.vendasImobiliarias,...(clean.propostas||[]),...(clean.contratos||[])].flatMap(record=>(record.documentos||[]).map(document=>({...document,reference:record.nome||record.codigo||record.titulo||record.numero||"Registro comercial"})));
    content=<><Header eyebrow="Dossiê imobiliário" title="Documentos" description="Materiais, plantas, propostas, reservas, contratos e evidências reunidos."/><div className="re-list">{documents.map((document,index)=><article key={document.id||index}><FileText size={18}/><div><strong>{document.nome||document.legenda||"Documento"}</strong><p>{document.reference}</p></div>{document.url&&<a className="re-btn re-btn--ghost" href={document.url} target="_blank" rel="noreferrer">Abrir</a>}</article>)}{!documents.length&&<Empty>Nenhum documento comercial anexado.</Empty>}</div></>;
  }else if(section==="reports"){
    content=<><Header eyebrow="Inteligência comercial" title="Relatórios" description="Inventário, VGV, disponibilidade, vendas, recebimentos e comissões."/><div className="re-report-grid">{clean.empreendimentos.map(dev=>{const units=clean.unidadesImobiliarias.filter(item=>item.empreendimentoId===dev.id);const sales=clean.vendasImobiliarias.filter(sale=>units.some(unit=>unit.id===sale.unidadeId));return <article key={dev.id}><h3>{dev.nome}</h3><dl><div><dt>Unidades</dt><dd>{units.length}</dd></div><div><dt>Disponíveis</dt><dd>{units.filter(item=>item.status==="disponivel").length}</dd></div><div><dt>Vendidas</dt><dd>{units.filter(item=>item.status==="vendida").length}</dd></div><div><dt>VGV disponível</dt><dd>{money(units.filter(item=>item.status==="disponivel").reduce((sum,item)=>sum+number(item.valorTabela),0))}</dd></div><div><dt>Vendas</dt><dd>{money(sales.reduce((sum,item)=>sum+number(item.valor),0))}</dd></div><div><dt>Recebido</dt><dd>{money(sales.reduce((sum,item)=>sum+number(item.valorRecebido),0))}</dd></div></dl></article>})}{!clean.empreendimentos.length&&<Empty>Cadastre empreendimentos e unidades para gerar os relatórios.</Empty>}</div></>;
  }else content=<Empty>Abra uma seção comercial.</Empty>;

  return <section className="re-commercial">{content}
    {modal==="development"&&<Dialog title={form.id?"Editar empreendimento":"Novo empreendimento"} onClose={()=>setModal(null)} onSubmit={saveDevelopment}><Field label="Código"><Input value={form.codigo||""} onChange={e=>set("codigo",e.target.value)}/></Field><Field label="Nome comercial"><Input required value={form.nome||""} onChange={e=>set("nome",e.target.value)}/></Field><Field label="Razão social / SPE"><Input value={form.spe||""} onChange={e=>set("spe",e.target.value)}/></Field><Field label="CNPJ da SPE"><Input value={form.cnpjSpe||""} onChange={e=>set("cnpjSpe",e.target.value)}/></Field><Field label="Status"><Select value={form.status||"estudo"} onChange={e=>set("status",e.target.value)} options={DEVELOPMENT_STATUSES}/></Field><Field label="Obra vinculada"><Select value={form.obraId||""} onChange={e=>set("obraId",e.target.value)} options={[{value:"",label:"Sem vínculo"},...obras.map(work=>({value:work.id,label:work.name}))]}/></Field><Field label="Endereço" wide><Input value={form.endereco||""} onChange={e=>set("endereco",e.target.value)}/></Field><Field label="Registro de incorporação"><Input value={form.registroIncorporacao||""} onChange={e=>set("registroIncorporacao",e.target.value)}/></Field><Field label="Matrícula principal"><Input value={form.matriculaPrincipal||""} onChange={e=>set("matriculaPrincipal",e.target.value)}/></Field><Field label="Lançamento"><Input type="date" value={form.dataLancamento||""} onChange={e=>set("dataLancamento",e.target.value)}/></Field><Field label="Previsão de entrega"><Input type="date" value={form.previsaoEntrega||""} onChange={e=>set("previsaoEntrega",e.target.value)}/></Field><Field label="VGV total"><Input type="number" value={form.vgvTotal||""} onChange={e=>set("vgvTotal",e.target.value)}/></Field><Field label="Quantidade de unidades"><Input type="number" value={form.quantidadeUnidades||""} onChange={e=>set("quantidadeUnidades",e.target.value)}/></Field><Field label="Comissão padrão %"><Input type="number" value={form.comissaoPadrao||""} onChange={e=>set("comissaoPadrao",e.target.value)}/></Field><Field label="Responsável comercial"><Select value={form.responsavelId||""} onChange={e=>set("responsavelId",e.target.value)} options={[{value:"",label:"Selecione"},...users.map(user=>({value:user.id,label:user.nome}))]}/></Field><Field label="Descrição comercial" wide><textarea value={form.descricao||""} onChange={e=>set("descricao",e.target.value)}/></Field><Field label="Diferenciais" wide><textarea value={form.diferenciais||""} onChange={e=>set("diferenciais",e.target.value)}/></Field></Dialog>}
    {modal==="unit"&&<Dialog title={form.id?"Editar unidade":"Nova unidade"} onClose={()=>setModal(null)} onSubmit={saveUnit}><Field label="Empreendimento"><Select required value={form.empreendimentoId||""} onChange={e=>set("empreendimentoId",e.target.value)} options={[{value:"",label:"Selecione"},...clean.empreendimentos.map(dev=>({value:dev.id,label:dev.nome}))]}/></Field><Field label="Código"><Input required value={form.codigo||""} onChange={e=>set("codigo",e.target.value)}/></Field><Field label="Bloco / torre"><Input value={form.bloco||form.torre||""} onChange={e=>set("bloco",e.target.value)}/></Field><Field label="Pavimento"><Input value={form.pavimento||""} onChange={e=>set("pavimento",e.target.value)}/></Field><Field label="Número"><Input value={form.numero||""} onChange={e=>set("numero",e.target.value)}/></Field><Field label="Tipologia"><Input value={form.tipologia||""} onChange={e=>set("tipologia",e.target.value)}/></Field><Field label="Quartos"><Input type="number" value={form.quartos||""} onChange={e=>set("quartos",e.target.value)}/></Field><Field label="Suítes"><Input type="number" value={form.suites||""} onChange={e=>set("suites",e.target.value)}/></Field><Field label="Banheiros"><Input type="number" value={form.banheiros||""} onChange={e=>set("banheiros",e.target.value)}/></Field><Field label="Vagas"><Input type="number" value={form.vagas||""} onChange={e=>set("vagas",e.target.value)}/></Field><Field label="Área privativa m²"><Input type="number" value={form.areaPrivativa||""} onChange={e=>set("areaPrivativa",e.target.value)}/></Field><Field label="Área total m²"><Input type="number" value={form.areaTotal||""} onChange={e=>set("areaTotal",e.target.value)}/></Field><Field label="Valor de tabela"><Input type="number" value={form.valorTabela||""} onChange={e=>set("valorTabela",e.target.value)}/></Field><Field label="Valor mínimo"><Input type="number" value={form.valorMinimo||""} onChange={e=>set("valorMinimo",e.target.value)}/></Field><Field label="Comissão %"><Input type="number" value={form.comissaoPct||""} onChange={e=>set("comissaoPct",e.target.value)}/></Field><Field label="Status"><Select value={form.status||"disponivel"} onChange={e=>set("status",e.target.value)} options={UNIT_STATUSES}/></Field><Field label="Posição / vista"><Input value={form.vista||""} onChange={e=>set("vista",e.target.value)}/></Field><Field label="Orientação solar"><Input value={form.orientacaoSolar||""} onChange={e=>set("orientacaoSolar",e.target.value)}/></Field><Field label="Observações" wide><textarea value={form.observacoes||""} onChange={e=>set("observacoes",e.target.value)}/></Field></Dialog>}
    {modal==="property"&&<Dialog title={form.id?"Editar imóvel":"Novo imóvel"} onClose={()=>setModal(null)} onSubmit={saveProperty}><Field label="Código"><Input value={form.codigo||""} onChange={e=>set("codigo",e.target.value)}/></Field><Field label="Título do anúncio"><Input required value={form.titulo||""} onChange={e=>set("titulo",e.target.value)}/></Field><Field label="Tipo"><Select value={form.tipo||"casa"} onChange={e=>set("tipo",e.target.value)} options={PROPERTY_TYPES}/></Field><Field label="Natureza"><Select value={form.natureza||"proprio"} onChange={e=>set("natureza",e.target.value)} options={PROPERTY_NATURES}/></Field><Field label="Proprietário"><Input value={form.proprietario||""} onChange={e=>set("proprietario",e.target.value)}/></Field><Field label="Contato do proprietário"><Input value={form.contatoProprietario||""} onChange={e=>set("contatoProprietario",e.target.value)}/></Field><Field label="Endereço" wide><Input value={form.endereco||""} onChange={e=>set("endereco",e.target.value)}/></Field><Field label="Valor de venda"><Input type="number" value={form.valorVenda||""} onChange={e=>set("valorVenda",e.target.value)}/></Field><Field label="Valor mínimo"><Input type="number" value={form.valorMinimo||""} onChange={e=>set("valorMinimo",e.target.value)}/></Field><Field label="Comissão %"><Input type="number" value={form.comissaoPct||""} onChange={e=>set("comissaoPct",e.target.value)}/></Field><Field label="Área construída m²"><Input type="number" value={form.areaConstruida||""} onChange={e=>set("areaConstruida",e.target.value)}/></Field><Field label="Área do terreno m²"><Input type="number" value={form.areaTerreno||""} onChange={e=>set("areaTerreno",e.target.value)}/></Field><Field label="Quartos"><Input type="number" value={form.quartos||""} onChange={e=>set("quartos",e.target.value)}/></Field><Field label="Suítes"><Input type="number" value={form.suites||""} onChange={e=>set("suites",e.target.value)}/></Field><Field label="Banheiros"><Input type="number" value={form.banheiros||""} onChange={e=>set("banheiros",e.target.value)}/></Field><Field label="Vagas"><Input type="number" value={form.vagas||""} onChange={e=>set("vagas",e.target.value)}/></Field><Field label="Matrícula"><Input value={form.matricula||""} onChange={e=>set("matricula",e.target.value)}/></Field><Field label="Exclusividade até"><Input type="date" value={form.exclusividadeAte||""} onChange={e=>set("exclusividadeAte",e.target.value)}/></Field><Field label="Descrição" wide><textarea value={form.descricao||""} onChange={e=>set("descricao",e.target.value)}/></Field></Dialog>}
    {modal==="reservation"&&<Dialog title="Nova reserva" onClose={()=>setModal(null)} onSubmit={saveReservation}><Field label="Unidade"><Select required value={form.unidadeId||""} onChange={e=>set("unidadeId",e.target.value)} options={[{value:"",label:"Selecione"},...clean.unidadesImobiliarias.filter(unit=>unit.status==="disponivel").map(unit=>({value:unit.id,label:assetName(clean,unit.id,"")}))]}/></Field><Field label="Lead"><Select value={form.leadId||""} onChange={e=>set("leadId",e.target.value)} options={[{value:"",label:"Selecione"},...(clean.leads||[]).map(lead=>({value:lead.id,label:lead.nome}))]}/></Field><Field label="Cliente"><Select value={form.clienteId||""} onChange={e=>set("clienteId",e.target.value)} options={[{value:"",label:"Selecione"},...(clean.clientes||[]).map(client=>({value:client.id,label:client.nome||client.razaoSocial}))]}/></Field><Field label="Corretor"><Select value={form.corretorId||""} onChange={e=>set("corretorId",e.target.value)} options={[{value:"",label:"Selecione"},...clean.corretores.map(item=>({value:item.id,label:item.nome}))]}/></Field><Field label="Valor"><Input required type="number" value={form.valor||""} onChange={e=>set("valor",e.target.value)}/></Field><Field label="Validade"><Input required type="date" value={form.validade||""} onChange={e=>set("validade",e.target.value)}/></Field><Field label="Observações" wide><textarea value={form.observacoes||""} onChange={e=>set("observacoes",e.target.value)}/></Field></Dialog>}
    {modal==="sale"&&<Dialog title="Registrar venda" onClose={()=>setModal(null)} onSubmit={saveSale}><Field label="Imóvel"><Select required value={form.asset||""} onChange={e=>set("asset",e.target.value)} options={[{value:"",label:"Selecione"},...clean.unidadesImobiliarias.filter(unit=>unit.status!=="vendida").map(unit=>({value:`unit:${unit.id}`,label:assetName(clean,unit.id,"")})),...clean.imoveisAvulsos.filter(item=>item.status!=="vendido").map(item=>({value:`property:${item.id}`,label:item.titulo}))]}/></Field><Field label="Cliente"><Select value={form.clienteId||""} onChange={e=>set("clienteId",e.target.value)} options={[{value:"",label:"Selecione"},...(clean.clientes||[]).map(client=>({value:client.id,label:client.nome||client.razaoSocial}))]}/></Field><Field label="Lead"><Select value={form.leadId||""} onChange={e=>set("leadId",e.target.value)} options={[{value:"",label:"Selecione"},...(clean.leads||[]).map(lead=>({value:lead.id,label:lead.nome}))]}/></Field><Field label="Corretor"><Select value={form.corretorId||""} onChange={e=>set("corretorId",e.target.value)} options={[{value:"",label:"Selecione"},...clean.corretores.map(item=>({value:item.id,label:item.nome}))]}/></Field><Field label="Valor da venda"><Input required type="number" value={form.valor||""} onChange={e=>set("valor",e.target.value)}/></Field><Field label="Valor recebido"><Input type="number" value={form.valorRecebido||""} onChange={e=>set("valorRecebido",e.target.value)}/></Field><Field label="Comissão %"><Input type="number" value={form.comissaoPct||""} onChange={e=>set("comissaoPct",e.target.value)}/></Field><Field label="Data da venda"><Input type="date" value={form.fechadaEm||""} onChange={e=>set("fechadaEm",e.target.value)}/></Field><Field label="Aprovação abaixo do mínimo" wide><label className="re-check"><input type="checkbox" checked={form.aprovadoAbaixoMinimo===true} onChange={e=>set("aprovadoAbaixoMinimo",e.target.checked)}/> Aprovação administrativa registrada</label></Field></Dialog>}
    {modal==="broker"&&<Dialog title={form.id?"Editar corretor":"Novo corretor"} onClose={()=>setModal(null)} onSubmit={saveBroker}><Field label="Nome"><Input required value={form.nome||""} onChange={e=>set("nome",e.target.value)}/></Field><Field label="CRECI"><Input value={form.creci||""} onChange={e=>set("creci",e.target.value)}/></Field><Field label="Tipo"><Select value={form.tipo||"interno"} onChange={e=>set("tipo",e.target.value)} options={["interno","parceiro","imobiliaria"]}/></Field><Field label="Comissão padrão %"><Input type="number" value={form.comissaoPadrao||""} onChange={e=>set("comissaoPadrao",e.target.value)}/></Field><Field label="Telefone"><Input value={form.telefone||""} onChange={e=>set("telefone",e.target.value)}/></Field><Field label="E-mail"><Input type="email" value={form.email||""} onChange={e=>set("email",e.target.value)}/></Field></Dialog>}
    {modal==="visit"&&<Dialog title={form.id?"Editar visita":"Nova visita"} onClose={()=>setModal(null)} onSubmit={saveVisit}><Field label="Lead"><Select value={form.leadId||""} onChange={e=>set("leadId",e.target.value)} options={[{value:"",label:"Selecione"},...(clean.leads||[]).map(lead=>({value:lead.id,label:lead.nome}))]}/></Field><Field label="Unidade"><Select value={form.unidadeId||""} onChange={e=>set("unidadeId",e.target.value)} options={[{value:"",label:"Selecione"},...clean.unidadesImobiliarias.map(unit=>({value:unit.id,label:assetName(clean,unit.id,"")}))]}/></Field><Field label="Corretor"><Select value={form.corretorId||""} onChange={e=>set("corretorId",e.target.value)} options={[{value:"",label:"Selecione"},...clean.corretores.map(item=>({value:item.id,label:item.nome}))]}/></Field><Field label="Data"><Input required type="date" value={form.data||""} onChange={e=>set("data",e.target.value)}/></Field><Field label="Hora"><Input type="time" value={form.hora||""} onChange={e=>set("hora",e.target.value)}/></Field><Field label="Status"><Select value={form.status||"agendada"} onChange={e=>set("status",e.target.value)} options={["agendada","confirmada","realizada","cancelada"]}/></Field><Field label="Observações" wide><textarea value={form.observacoes||""} onChange={e=>set("observacoes",e.target.value)}/></Field></Dialog>}
  </section>;
}
