import "../styles/portal.css";

const currency = value => new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL" }).format(Number(value || 0));
const date = value => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle:"medium" }).format(new Date(`${value}T12:00:00`)) : "—";

export function ClientFinancialPage({ data = {} }) {
  const summary = data.financialSummary?.[0];
  const measurements = data.measurements || [];
  const payments = data.payments || [];
  return <div className="arcd-client-page"><header className="arcd-client-page__header"><p>Contrato</p><h2>Financeiro compartilhado</h2><span>Resumo contratual publicado pela equipe. Não contém custos internos, pagamentos de equipe ou dados bancários.</span></header>{summary ? <section className="arcd-client-financial-grid" aria-label="Resumo financeiro contratual"><article><span>Contrato atual</span><strong>{currency(summary.contractCurrent)}</strong><small>Original {currency(summary.contractOriginal)} · alterações aprovadas {currency(summary.approvedChanges)}</small></article><article><span>Medido</span><strong>{currency(summary.measured)}</strong><small>Aprovado {currency(summary.approved)}</small></article><article><span>Pago</span><strong>{currency(summary.paid)}</strong><small>Em aberto {currency(summary.openAmount)}</small></article><article><span>Saldo a medir</span><strong>{currency(summary.balanceToMeasure)}</strong><small>Atualizado em {date(summary.asOf)}</small></article></section> : <section className="arcd-client-section"><h2>Resumo financeiro</h2><p className="arcd-client-muted">O resumo contratual ainda não foi publicado.</p></section>}<section className="arcd-client-section"><h2>Medições publicadas</h2>{measurements.length ? <div className="arcd-client-stack">{measurements.map(item => <article className="arcd-client-record" key={item.id}><div className="arcd-client-record__heading"><div><p className="arcd-client-record__eyebrow">{item.period || "Medição"} · {item.status || "Publicada"}</p><h3>{item.number || "Medição"}</h3></div><b>{currency(item.amount)}</b></div>{item.description && <p>{item.description}</p>}<p>Vencimento: {date(item.dueDate)} · Avanço informado: {Number(item.percentage || 0)}%</p>{item.documentUrl && <a className="arcd-client-link" href={item.documentUrl} target="_blank" rel="noreferrer">Abrir documento publicado</a>}</article>)}</div> : <p className="arcd-client-muted">Nenhuma medição foi compartilhada.</p>}</section><section className="arcd-client-section"><h2>Recebimentos publicados</h2>{payments.length ? <div className="arcd-client-stack">{payments.map(item => <article className="arcd-client-record" key={item.id}><div className="arcd-client-record__heading"><div><p className="arcd-client-record__eyebrow">{item.status || "Registrado"}</p><h3>{item.description || "Recebimento"}</h3></div><b>{currency(item.amount)}</b></div><p>Vencimento: {date(item.dueDate)}</p>{item.receiptUrl && <a className="arcd-client-link" href={item.receiptUrl} target="_blank" rel="noreferrer">Abrir comprovante publicado</a>}</article>)}</div> : <p className="arcd-client-muted">Nenhum recebimento foi publicado.</p>}</section></div>;
}
