import "../styles/portal.css";

function ProgressSummary({ project }) { return <section className="arcd-client-progress"><span>Execução geral</span><strong>{Math.max(0, Math.min(100, Number(project.progress || 0)))}%</strong><div aria-label={`${project.progress || 0}% executado`} role="progressbar" aria-valuenow={Number(project.progress || 0)} aria-valuemin="0" aria-valuemax="100"><i style={{ width:`${Math.max(0, Math.min(100, Number(project.progress || 0)))}%` }} /></div><p>{project.currentPhase || "Fase em atualização"}</p></section>; }
function PendingActions({ decisions = [], measurements = [], media = [] }) { const pending = [[decisions.length, "decisão(ões) aguardando você"], [measurements.length, "medição(ões) disponível(is)"], [media.length, "nova(s) mídia(s) publicada(s)"]].filter(([amount]) => amount > 0); return <section className="arcd-client-section"><h2>O que precisa da sua atenção</h2>{pending.length ? <ul className="arcd-client-pending">{pending.map(([amount, label]) => <li key={label}><strong>{amount}</strong><span>{label}</span></li>)}</ul> : <p className="arcd-client-muted">Nenhuma decisão pendente neste momento.</p>}</section>; }
function WeeklyUpdate({ update }) { if (!update) return null; return <section className="arcd-client-weekly"><p>Última atualização</p><h2>{update.period || "Resumo da semana"}</h2><span>{update.summary || "A equipe ainda não publicou um resumo."}</span>{update.nextSteps?.length > 0 && <p className="arcd-client-muted">Próximo: {update.nextSteps[0]}</p>}</section>; }

export function ClientDashboard({ data }) {
  const project = data.project || {};
  return <div className="arcd-client-dashboard"><section className="arcd-client-hero" style={project.coverImage ? { backgroundImage:`linear-gradient(90deg, rgba(21,25,29,.72), rgba(21,25,29,.2)), url(${project.coverImage})` } : undefined}><p>ARCD Construtech</p><h2>{project.name}</h2><span>Previsão atual: {project.estimatedCompletion || "a confirmar"}</span></section><ProgressSummary project={project} /><PendingActions decisions={data.decisions} measurements={data.measurements} media={data.publishedMedia} /><WeeklyUpdate update={data.weeklyUpdates?.[0]} /></div>;
}
